Feature/1
Bodichane/POO pull request #2
Opened 2023-03-20 22:13 UTC by Bodichane

2023-03-23 16:03 UTC, MarinaPaley requested changes
1. Отсутствует документация
2. Неправильно названы файлы. Нужно использовать "говорящие" имена: 
`Form.sln/ Circle.proj/ Circle.h, Circle.cpp, Point.h, Point.cpp`

2023-03-23 16:03 UTC, MarinaPaley commented on Task/Task-1/Point.h
> +		Point(unsigned int x, unsigned int y);
`Point(unsigned int x = 0, unsigned int y = 0);`  и не нужен пустой конструктор

2023-03-23 16:03 UTC, MarinaPaley commented on Task/Task-1/Point.cpp
> +Point::Point(unsigned int, unsigned int y) : x(x), y(y) {}
Если на вход конструктора подать `-1`, то произойдет преобразование к `usigned int` и [число будет большим](https://replit.com/@MarinaPaley/IllLovableOperatingsystem)
![image](https://user-images.githubusercontent.com/26978698/227258353-6c76abd1-4034-41a7-a1fa-07ac3d70c0e0.png)

2023-03-23 16:03 UTC, MarinaPaley commented on Task/Task-1/Circle.cpp
> +    std::string dummy;
Точно так? Или так `std::string dummy = ' ';`

2023-03-23 16:03 UTC, MarinaPaley commented on Task/Task-1/Circle.h
> +		static void ValidateAndThrow(unsigned int radius);
Почему `static`?
Почему `public`?
И почему не в конструкторе?
Создавать объект нужно сразу валидным или не создавать его совсем!

2023-03-23 16:03 UTC, MarinaPaley commented on Task/Task-1/Circle.h
> +class Circle : public Form, Point
Неправильная архитектура!
Автомобиль не наследуется от руля, человек не наследуется от сердца, Окружность не наследуется от центра!!!

2023-03-23 16:03 UTC, MarinaPaley commented on Task/Task-1/Form.h
> +        virtual ~Form();
`virtual ~Form() = 0;`

2023-03-23 16:03 UTC, MarinaPaley commented on Task/Task-1/Form.h
> +        virtual void Draw() const;
они дублируются

2023-03-23 16:03 UTC, MarinaPaley commented on Task/Task-1/main.cpp
> +    Circle::ValidateAndThrow(10);
Никогда пользователь не будет действовать так! Ему и в голову не придет что-то проверять! Это НЕ удобно. Вся проверка должна быть внутри конструктора.

2023-04-01 20:59 UTC, Bodichane commented
В какой файл я поместил документацию?

2023-04-02 17:10 UTC, MarinaPaley commented
@Bodichane а я не знаю, в какой файл ВЫ поместили документацию.

2023-04-04 09:15 UTC, MarinaPaley requested changes

2023-04-04 09:15 UTC, MarinaPaley commented on Task/Task-1/Circle.cpp
> +Circle::Circle(unsigned int radius, const Point& center) : radius(radius), center(center)
`Circle::Circle(int radius, const Point& center)`

2023-04-04 09:15 UTC, MarinaPaley commented on Task/Task-1/Circle.h
> +	     	* @param center The center of the circle.
`@throws std::invalid_argument when radius is negatiive`

2023-04-04 09:15 UTC, MarinaPaley commented on Task/Task-1/Point.cpp
> +    if (x > 0 && x < 1290 && y > 0 && y < 1080)
Не надо использовать _&laquo;магические константы&raquo;_ в коде. Это не только признак дурновкусия, но и источник большого числа потенциальных ошибок. Привожу некоторые источники, потребные для Вашего самообразования:
- [ru.wikipedia.org](https://ru.wikipedia.org/wiki/Магическое_число_(программирование))
- [refactoring.guru](https://refactoring.guru/ru/replace-magic-number-with-symbolic-constant)
- [pvs-studio.com](https://pvs-studio.com/ru/blog/posts/cpp/0023/)
- [habr.com](https://habr.com/ru/post/328244/)

убрать константы

2023-04-04 09:15 UTC, MarinaPaley commented on Task/Task-1/Point.cpp
> +    }
только проверка на то, что все плохо и выброс исключения

2023-04-04 09:15 UTC, MarinaPaley commented on Task/Task-1/Point.h
> +		Point(unsigned int x = 0, unsigned int y = 0);
`Point(int x = 0, int y = 0);`

2023-04-04 09:15 UTC, MarinaPaley commented on Task/Task-1/Point.h
> +	friend bool operator==(const Point& lhs, const Point& rhs);
[`spaceship c++20`](https://en.cppreference.com/w/cpp/language/default_comparisons)

2023-04-04 10:09 UTC, MarinaPaley approved these changes

2023-04-04 10:14 UTC, merged